[package]
name = "bevy_water_shaders"
version = "0.1.0"
authors = ["Nick Hughes <nickjhughes@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.11"
bevy_egui = "0.21"
bevy_turborand = "0.6"
